sei-uxdi-collab/work_from_roam-client

src/components/App.js
src/components/ReviewForm.js

The form component allows user input for reviewing and rating.

Created ReviewForm component

---

package-lock.json
package.json
src/components/App.js
src/components/ReviewForm.css
src/components/ReviewForm.js
src/components/TestButton.js

Route for '/new/:placeId' shows the review form on top of the map.
Route for '/' just shows the map.

Routes for '/' and '/new/:placeId'

---

src/components/ReviewForm.js

located top-right corner of the component

Update close button on ReviewForm component

---

src/components/GoogleMap.js

Center map when user clicks on poi

---

src/apiConfig.js
src/components/App.js
src/components/GoogleMap.js
src/components/Search.js

1. Three different markers for `userLocation`, `searchLocation`, and
`workSpace`
2. Fixed Search component by updating query with the correct states being
passed down from the App component level

Added three different markers

---

src/components/Search.css
src/components/Search.js

- fix styling for search autocomplete suggestions
- clear form on handleAutocompleteSelect
closes #26

Fix Search bugs

---

src/components/App.js
src/components/GoogleMap.js
src/components/Search.js

`mapCenter` is updated once  user location or search result is found

Updating `mapCenter`

---

src/components/ChangePassword/ChangePassword.css
src/components/ReviewForm.css
src/components/SignIn/SignIn.css
src/components/SignUp/SignUp.css

Update component styling

---

src/components/ReviewForm.js

Implemented the
name of the place,
an image and
the website of the location that is attached to the image.

Updated the Review Component with place details

---

src/components/App.js
src/components/GoogleMap.js
src/components/Review/Review.js
src/components/WorkSpace/WorkSpace.css
src/components/WorkSpace/WorkSpace.js

Workspace displays name, image, link to website, and reviews
Created a route for '/workspace' which displays the workspace component

Created Workspace component

---

src/components/App.js
src/components/GoogleMap.js
src/components/SuggestionsList/SuggestionsList.css
src/components/SuggestionsList/SuggestionsList.js

Initial suggestions list feature.

Added initial suggestion list component.

---

src/components/WorkSpace/WorkSpace.css
src/components/WorkSpace/WorkSpace.js

Needs work!! Having trouble with spacing of reviews and review link

Worked on some styling for WorkSpace

---

src/components/Review/Review.js
src/components/Review/ReviewCreate.js
src/components/WorkSpace/WorkSpace.js

Worked on a few details. Nothing huge.

Geoff workspace

---

src/components/Review/ReviewCreate.js
src/components/WorkSpace/WorkSpace.js

I was able to get the filter buttons to change depending on the average number of y/n answers was above 0.
We probably need to adjust the logic of this, but the method is pretty sound... I think.

Coffee Food and Outlets conditional

---

src/apiConfig.js

Updated the heroku url. That is all.

Changed the heroku URL

---

src/components/App/App.js
src/components/Review/ReviewCreate.js
src/components/WorkSpace/WorkSpaceCreate.js

pass setApp to ReviewCreate and WorkSpaceCreate
make call to API GET all data
setApp with the updated data on successfull workspace and review create

Update `allData` on workspace create and review create

---

src/apiConfig.js
src/components/GoogleMap/GoogleMap.js
src/components/GoogleMap/GoogleMap.scss
src/components/Header/Header.js
src/components/Header/Header.scss
src/components/NavBar/NavBar.js
src/components/NavBar/NavBar.scss
src/components/Search/Search.scss

Improved on styling of the search bar to match UX wireframes.
Still needs work but moving closer to the design.

Search bar

---

src/components/Header/Header.js
src/components/Header/Header.scss

Stripped down the component some, so it functions better now that we are using Bootstrap.
Still needs styling. 
Waiting on UXDI for some final designs.

Re-configured Header.js to account for Bootstrap

---

src/components/GoogleMap/GoogleMap.js
src/components/WorkSpace/WorkSpaceCreate.js

Consolidated interaction with Google Places API to `this.getPlacesDetail` and more refactoring in GoogleMap.js
navigate to '/create-workspace' on POI click
minor updates to WorkSpaceCreate component. More work to be done on this component.

Googlemap refactor

---

src/components/GoogleMap/GoogleMap.js

Google places api will return 'opening_hours' for all places detail requests

Add 'opening_hours' as a field to placeData

---

src/components/AutoAlert/AutoAlert.js
src/components/GoogleMap/GoogleMap.js

click on AutoAlert to close the Alert.  We can update or change behavior with `onClick` prop

Alex auto alert

---

src/components/App/App.js
src/components/ListView/ListView.js
src/components/ListView/ListView.scss
src/components/ListView/WorkspaceCarousel.js
src/components/ListView/WorkspaceCarousel.scss

Re-factored ListView.js/.scss to leverage react-bootstrap for responsiveness across screen sizes. Added method in ListView.js to close the list view when user clicks outside the component as well as the header. Added WorkspaceCarousel component within the list view, which will eventually display workspace details based on selected filters.

Rick list view

---

package-lock.json
package.json
src/components/App/App.js
src/components/App/App.scss
src/components/NavBar/NavBar.scss
src/components/Search/Search.scss
src/components/WorkspaceFilter/WorkspaceFilter.js
src/components/WorkspaceFilter/WorkspaceFilter.scss

Completed initial filter component styling and UI functionality. User selections are stored in a "filters" object, which can eventually be implemented in an Axios call to GET relevant workspaces based on selection criteria.

Rick workspace filter

---

src/components/GoogleMap/GoogleMap.js
src/components/WorkSpace/WorkSpaceCreate.js

1. add options to GoogleMap to update gestureHandling to 'greedy'
this should allow 1-touch scrolling on mobile
2. Remove redirect to '/sign-in' on WorkSpaceCreate component
3. deprecate infoWindow behavior

Updates to user interface and experience

---

src/components/AutoAlert/AutoAlert.js

Fix bug with alert image on mobile

Set alert image to width='100%'

---

src/components/Review/Review.js
src/components/WorkSpace/ScaleRating.js
src/components/WorkSpace/ScaleRating.scss
src/components/WorkSpace/WorkSpace.js

One more step closer to the wireframes! A few things we still have to determine:
1) I adjusted the placement of the stars rating within each individual review to allow for longer username. This may be something we put a limit on in terms of how long a username can be... thoughts, @GMorse19? Since we'll have to update back end with user profile feature eventually. (Obv, the limit will most likely be done via front end. But something to discuss.)
2) How do we want to display data for noise level within the scale rating? I touched on this a little bit in our Slack dm. Will pass this on to the designers for their input. 
3) When a user review has no comments, do we want to display that? If chosen not to display, it will contradict the total review count.. could potentially SEEM false and …

Ying scale rating

---

src/components/ChangePassword/ChangePassword.js
src/components/ChangePassword/ChangePassword.scss
src/components/Review/ReviewCreate.js
src/components/Review/ReviewCreate.scss
src/components/SignIn/SignIn.js
src/components/SignIn/SignIn.scss
src/components/SignUp/SignUp.js
src/components/SignUp/SignUp.scss

Spacing is still responsive
Changes are in ReviewCreate, SignIn, SignUp, ChangePassword
Changed the name of ReviewCreate.scss

Changed some responsiveness styling back to pixels

---

src/components/WorkSpace/WorkSpaceCreate.js

Redirect to '/sign-in' if user not logged in

---

src/components/App/App.js
src/components/AutoAlert/AutoAlert.js
src/components/AutoAlert/AutoAlert.scss
src/components/ChangePassword/ChangePassword.js
src/components/SignIn/SignIn.js
src/components/SignOut/SignOut.js
src/components/SignUp/SignUp.js

Failure alerts are given variant='danger'
added className={variant} to Alert and .danger class to style failure alerts
Failure alerts will appear at the top of the page
All other alerts will remain centered on the page
Alerts will only take up the space they need

Update auto-alerts fixes #116

---

src/components/App/App.js
src/components/WorkSpace/WorkSpaceCreate.js

- withRouter was overwriting our 'location' prop
- changed 'location' to 'workspaceLocation'
- added fields for name, address, and photo

Alex create workspace update fields

---

src/components/Review/Review.js
src/components/Review/Review.scss
src/components/WorkSpace/WorkSpace.js
src/components/WorkSpace/WorkSpace.scss

Ying workspace (username and long/empty reviews)

---

src/App.test.js
src/helpers/calculateDistance.js

Accepts 2 or 3 arguments: location1, location2, and optional # of decimals
Returns the number of miles rounded to the specified decimals, or 1 decimal if not specified
import { calculateDistanceMiles } from './helpers/calculateDistance'

Export function to calculate distance

---

src/components/WorkspaceFilter/WorkspaceFilter.js
src/components/WorkspaceFilter/WorkspaceFilter.scss

Initial functionality of the new workspace filter to match UI/UX designs FOR DESKTOP ONLY. Currently, user can toggle all of the filter buttons on/off, and the 'submit' button will print out the filters state to the console, reset all filters, and then close the modal.
Next steps:
1. Complete styling to match wireframes exactly
- How to center text vertically in buttons? Why isn't this straightforward?
2. Hook up the Submit button to a GET call, and map the response to the ListView
3. Write second version of this filter component to match the design for XS screens

Completed initial styling and functionality of new workspace filter.

---

src/components/Header/Header.js
src/components/Header/Header.scss
src/components/Info/Info.js
src/components/Info/Info.scss

Added a snazzy new info component with toggle collapse functionality, and changed the location of change password within header to match figma drawings by UX team. 
Closes issue #126

Added Info Component to Header, and Change PW styling

---

src/components/Header/Header.js
src/components/Header/Header.scss
src/components/MyFavorites/MyFavorites.js
src/components/MyFavorites/MyFavorites.scss
src/components/TopRated/TopRated.js
src/components/TopRated/TopRated.scss

Added toggles for TopRated and MyFavorites with placeholder content. 
Also added signout button back in because somehow it got deleted in the last pull request... whoops!

Regina header

---

package-lock.json
package.json
src/api/workspaceFilter.js
src/components/App/App.js
src/components/Search/Search.js
src/components/WorkspaceFilter/WorkspaceFilter.js
src/components/WorkspaceFilter/WorkspaceFilter.scss

Completed initial styling differences between mobile and desktop views. Filter is now set up, and can be fine-tuned to work with the proper API call, when decided upon. Some minor additions still necessary on the mobile view.

Rick filter refactor

---

package.json
src/api/auth.js
src/components/SignIn/SignIn.js
src/components/SignUp/SignUp.js

apiconfig is still working off the deployed API. Alter path to work off the development branch of the API.

Geoff change auth

---

src/components/ListView/Dots.js
src/components/ListView/ListView.js
src/components/ListView/ListView.scss
src/components/ListView/ListViewRatings.js
src/components/ListView/Slide.js
src/components/WorkspaceFilter/WorkspaceFilter.js

Initial pass at card-like component in ListView

Completed first pass at card-like view for ListView components.

---

src/components/GoogleMap/GoogleMap.js
src/components/GoogleMap/GoogleMap.scss

- target InfoWindow classes and set to display: none
- remove code regarding InfoWindow

Deprecate InfoWindow

---

src/components/App/App.js
src/components/ListView/Slide.js
src/components/Search/Search.js
src/components/WorkspaceFilter/ApplyFilters.js
src/components/WorkspaceFilter/WorkspaceFilter.js

Completed initial filtering component (ApplyFilters.js). Returns only workspaces that match all of the selected filters. Summons an annoying pop-up alert if there are no matches, which DOES NOT clear the ListView.
Future work includes:
1. Implementing the sort feature in the ListView
2. Re-factoring the WorkspaceFilter with a better solution when no filter matches occur
3. Implement the correct distance from the user and open hours in the ListView
4. Limit number of filter results to a certain number, or distance radius?
5. Re-factor components for desktop view (very low priority)

Rick filter list view connect

---

src/components/Header/Header.js
src/components/Info/Info.js
src/components/MyFavorites/MyFavorites.js
src/components/MyReviews/MyReviews.js
src/components/TopRated/TopRated.js

- Refactored Header component
- Header state keeps track of active components
- Only one section can be active at once

Header state determines active

---

src/components/App/App.js
src/components/Header/Header.js
src/components/MyFavorites/MyFavorites.js
src/components/MyReviews/MyReviews.js
src/components/TopRated/TopRated.js

Arrow click will set the currentWorkplace and mapCenter.

Add on Arrow Click functionality to cards

---

src/api/update.js
src/components/App/App.js
src/components/MyReviews/MyReviews.js
src/components/Review/ReviewUpdate.js

Added a updateReview component. 
I added a route for this component, so there are a couple added lines in App.js
I also added a function (onUpdateClick) in MyReviews.js that will work with a button similar to:
```
<Button
href={`#reviews/${review.id}/update`}
onClick={() => onUpdateClick(review)}
>update</Button>
```
Nothing in the App will be affected until we place a button in, but the mechanics are all there.
The styling is basically the same as reviewCreate,  but the fields are pre-filled with the previous data... except for the booleans. I tried a few options for pre-filling the booleans, but ultimately it might be a better job for someone more familiar with toggleChange.

Geoff update review

---

src/api/create.js
src/components/Review/ReviewCreate.js

Added the newer attributes to reviewCreate.

Added new attributes to reviewCreate

---

src/components/SplashPage/SplashPage.js
src/components/SplashPage/SplashPage.scss

Made some adjustments to the Splash Page. This should correct the placement issue on mobile.

Adjusted splash page margintop

---

src/components/Header/Header.js
src/components/SplashPage/SplashPage.js
src/components/TopRated/TopRated.js

Removed token Authentication in TopRated.js
Added failsafe if userLocation is missing in
TopRated.js
Added TopRated component to unauthenticatedOptions in Header.js
Removed collapseOnSelect from Header.js(error message)
Added {to=""} in <Link> in SplashPage.js(error message)

Added top_rated to unauthenticatedOptions

---

src/components/App/App.js
src/components/GoogleMap/GoogleMap.js
src/components/Header/Header.js
src/components/MyFavorites/MyFavorites.js
src/components/MyReviews/MyReviews.js
src/components/TopRated/TopRated.js
src/helpers/googlePlaceDetails.js

arrow click redirects to the workspace component
App tracks { google, map } in state
outside components receive { google, map } as props
getGooglePlaceDetails is called with (google, map, placeId, callback)

Create helper to get google place details

---

src/apiConfig.js
src/components/App/App.js
src/components/Header/Header.js

This update uses `showUser` and `setUser` when Header.js is opened.
Added `setUser` to the Header.js route in App.js
Left apiconfig hack commented out to avoid any confusion until current api development branch is deployed.

Added showUser to Header.js updates user to most current state

---

src/components/Avatar/Avatar.js
src/components/Avatar/Avatar.scss

- convert avatar buttons to divs
- make scrollable at width less than 812px
- improve styling to match wireframes

Avatar styling

---

src/components/Header/Header.js
src/components/Header/Header.scss
src/components/MyFavorites/MyFavorites.js
src/components/MyFavorites/MyFavorites.scss
src/components/MyReviews/MyReviews.scss
src/components/Settings/Settings.scss
src/components/TopRated/TopRated.js
src/components/TopRated/TopRated.scss

On a new branch because merge conflicts were giving me issues... sorry! 
Phone number is also gone from toprated and myfavorites now.

Header screen sizes, and avatar changes

---

src/components/App/App.js
src/components/Header/Header.js
src/components/HeaderAuthOptions/HeaderAuthOptions.js
src/components/HeaderAuthOptions/HeaderSignIn/HeaderSignIn.js
src/components/HeaderAuthOptions/HeaderSignUp/HeaderSignUp.js

Passing `setUser` and `barAlert` into Header => HeaderAuthOptions => HeaderSignIn/HeaderSignUp

Header authentication

---

src/components/App/App.js
src/components/Header/Header.js
src/components/Header/Header.scss
src/components/HeaderAuthOptions/HeaderAuthOptions.js
src/components/HeaderAuthOptions/HeaderAuthOptions.scss
src/components/HeaderAuthOptions/HeaderSignIn/HeaderSignIn.js
src/components/HeaderAuthOptions/HeaderSignIn/HeaderSignIn.scss
src/components/HeaderAuthOptions/HeaderSignUp/HeaderSignUp.js
src/components/HeaderAuthOptions/HeaderSignUp/HeaderSignUp.scss
src/components/MyReviews/MyReviews.js

This branch is NOT COMPLETED and merging as is will cause the app to crash when a user attempts to authenticate. 
I currently don't know how to fix my issue, I'm making a pull request in case anyone needs to try it out to solve it. Error message is: 
Please let me know if you have any ideas! I think that I'm probably just passing down some info wrong but I don't know where or what

Added Sign In & Sign Up to header

---

src/components/Avatar/Avatar.js
src/components/Avatar/Avatar.scss

- component will initialize state with the group your avatar belongs to
- update styling to match wireframe and accomodate mobile

Avatar component styling and logic

---

src/components/Review/Review.scss
src/components/WorkSpace/WorkSpace.js
src/components/WorkSpace/WorkSpace.scss

- Fixed app crashing when photos are not found from Google Maps API
- Slight styling adjustment to cover some device specific issues

Ying workspace - bug fix

---

CNAME
package.json

Updated CNAME and homepage in order to deploy to custom URL.

Update custom url and CNAME workfromroam.co

---

src/components/Header/Header.js
src/components/HeaderAuthOptions/HeaderAuthOptions.js

-signIn starts true unless user is signed in
-only one section can be expanded at once
screenshot:
https://drive.google.com/file/d/1O-CeqyVMo_7LmCFWyOlLDZEuRQ-VkvCI/view

Unauthenticated header state

---

src/components/Search/Search.js
src/components/Search/Search.scss

Shortened dropdown container.
Some other minor adjustments.

Geoff srchbar

---

public/current-location-marker.svg
src/components/App/App.js
src/components/GoogleMap/GoogleMap.js
src/components/Search/Search.js

The new markers are now completely functional. Fixed bug by redirecting to homepage as discussed. Marker on `mapCenter` when app is loaded still appears. Would love to get rid of this.

Ying marker

---

src/components/Header/Header.js

fix minor top-rated styling defect in unauthenticated options

---

src/components/Review/ReviewCreate.scss

-Avoid confusion with list view on mobile

Add z-index to review

---

src/components/GoogleMap/GoogleMap.js
src/components/MapStyles.js

-Snazzy maps https://snazzymaps.com/style/287532/23-sul
Screenshot:

Add greyscale to map styles

---

src/components/WorkSpace/WorkSpace.js

The former conditionals did not target the proper data

Fixed app crashing if workspace has no photos available

---

src/components/MyReviews/MyReviews.js
src/components/Review/ReviewCreate.js
src/components/TopRated/TopRated.js

And took out some console logs. Not urgent for deployment. And does not include all errors/warnings.

Gave unique IDs to bootstrap forms

---

src/components/App/App.js
src/components/Carousel/Slide.js
src/components/ListView/ListView.scss
src/components/Search/Search.js
src/components/WorkspaceFilter/ApplyFilter.js
src/components/WorkspaceFilter/WorkspaceFilter.js
src/components/WorkspaceFilter/WorkspaceFilter.scss

Significant re-factoring to WorkspaceFilter.js and ApplyFilter.js, simplifying the former by removing the entire 'switch' statement. Modal now closes and filter is cleared when user clicks outside, and modal acts as expected.

Rick cleanup
